# Generated by Django 4.2.6 on 2024-10-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
